language: bash
env:
  global:
    - DEPLOY_HOST=rpm.palette-software.com
    - DEPLOY_PATH=/var/palette-rpm-repo
    - DEPLOY_USER=palette-rpm
    # DEPLOY_PASS
    - secure: "RepilBJLdVMlPcyjKuIqpOWOJfWefuqPBGGOCIZz83rp/k5POd0f9qEoRtcJa1gwk4eLNm0r/w4jW9ClBF3POErzGYNcI6r2VWzXGSRQWoyz7HWmQwcx06uPKuBp7T8bo9KJ3EIAaL+vEMcubntNuHw06LsVNY+YbGA/HWVpd8Pou6OGLFrRHiNNRFg8KPtymTgiHHJG+Bogo2V0AGxQJynad3rmd+7F2/0BANQ0s7VDIUj6VktTr5/QzJ/BUq1Z5bI9l8p/Izg30bvktCdSzA5Mqnhyo/QqMQYzrU+ZE8llJMa23F8N4psXwjIXCcczoJ/k+JDyJA0LUHeabreXrbV5jJ54dRCCIKgCnjh65VFYfh58mEbZwvPBmiZjH5auvrFaRfTahprJ82i1k8LrwoQwLk1t+IB/Kn0f4hlrG6+68r1bs4qJJR+v8HlaFozhEY3PKlvlWCzdoGHUDSnNSypUdS25UcEkdLZZV/2dNgwcnuNPXrPg6gAgW79cfiUNp2q5OxK0ZX/kNYiuZNiH3V3xMNDrrqsufFJzKaBvrBO6KCep+mGq4Mhgi/Jj1wHPqSaPNpT7TxYFcUeWvBPvRZli8l0ZGIVLPNO9AO8t3d7ti+TdgKHn83+AU87NLxcYYnEGxsYWj7Mo/7x+LaR8MQy2/4Ba1BL47nxyEqxDmEE="
    # GITHUB_TOKEN
    - secure: "QNrVw/wtzpqwng1P+FoAkWTRBWA5f2ZIPMOa/x8VSIPZc4J7vRqnIOXuD4qI8/W548782mAEEnFzPS1xyaT9qg7ARyuLmSojcKX3XuiMMF37jwrqlfN55+7JFL+aDDuUkMyfQiDLq6g70x7WIN3IqjheJcCHeshYObzfa7/h41P9LkOLer0jm5PymOe9zGpAbQwaIvBNN4xpOpIeyjUzWVfRm7WA9M6D4/W29nTIOQLRIZKacOy08LvMbgWOwGb1Gzy4UUKasbgYmYVcXilvlB+l4WQ8QLH0ZhstfW16g3rgjP71k/Wm1xCvpSscPXtLs46Cal+88OK1t0fysCRY+sbusaOPRChcuzdybv2eKjurjQAUDwDrw4b8iGYR2kd2q6hwmqScYIV+BAjIJUalUtOtEpY81XYSJlqODVeh1Bjxb8TjT1dLoclWyOadOtk+Ql5S884e3IayKwF0INvNnppLvyNgNxxXim8DSxPyOwcZ/Adrxt0tDc35fPT7o/4OTehDyoJXieujPqSvkFQJ+T3OxFgbrKqlTuL4Fx0zxxSa2wriuSdkiEAqGv9ulMKvSGszkFOdom0ObQ4d0PbwJ6H/wAaZkHsQ8Z5PhPKv0CIRSXNZJqlGWNeEkCQ2J03LNVB5I5kpJCW64/u9O0QTXOoIWtdf66qDxVIPK9EqaoI="
branches:
  only:
    - MANUAL_TRIGGER
addons:
  apt:
    packages:
      - rpm
      - sshpass
install: true
script:
  - rpmbuild -bb --buildroot $(pwd) -D "version ${PALETTE_AGENT_VERSION}" -D "github_token ${GITHUB_TOKEN}" -D "buildrelease 1" -D "_rpmdir rpm-build/_build" insight-agent.spec
deploy:
  provider: script
  script: ./deploy.sh
  skip_cleanup: true
  on:
    branch: master

notifications:
  email:
    on_success: never
    on_failure: never
